name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install next-js
        run: yarn install
        working-directory: nextjs/js
      - name: Build next-js
        run: yarn build
        working-directory: nextjs/js
      - name: Install next-ts
        run: yarn install
        working-directory: nextjs/ts
      - name: Build next-ts
        run: yarn build
        working-directory: nextjs/ts
      - name: Install parcel-js
        run: yarn install
        working-directory: parcel/js
      - name: Build parcel-js
        run: yarn build
        working-directory: parcel/js
      - name: Install parcel-ts
        run: yarn install
        working-directory: parcel/ts
      - name: Build parcel-ts
        run: yarn build
        working-directory: parcel/ts
      - name: Install vite-js
        run: yarn install
        working-directory: vite/js
      - name: Build vite-js
        run: yarn build
        working-directory: vite/js
      - name: Install vite-ts
        run: yarn install
        working-directory: vite/ts
      - name: Build vite-ts
        run: yarn build
        working-directory: vite/ts
      - name: Install webpack-js
        run: yarn install
        working-directory: webpack/js
      - name: Build webpack-js
        run: yarn build
        working-directory: webpack/js
      - name: Install webpack-ts
        run: yarn install
        working-directory: webpack/ts
      - name: Build webpack-ts
        run: yarn build
        working-directory: webpack/ts
      - name: Install node
        run: yarn install
        working-directory: node
      - name: Build node
        run: yarn build:ts && yarn run:js && yarn run:mjs && yarn run:ts && yarn run:ts-node
        working-directory: node
